2012/08/16 19:44:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:44:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:46:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:46:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:46:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:46:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:46:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 19:47:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "gii".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(271): CController->missingAction('gii')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('gii')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('site/gii')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/trackstar/index.php?r=site/gii
---
2012/08/16 19:49:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii.".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('gii.')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=gii.
---
2012/08/16 20:58:21 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('project/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=project/admin
HTTP_REFERER=http://localhost/trackstar/index.php?r=project
---
2012/08/16 21:17:23 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('project/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=project/admin
HTTP_REFERER=http://localhost/trackstar/index.php?r=project/index
---
2012/08/17 13:57:04 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('delete')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('issue/delete')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=issue/delete&id=1
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/view&id=1
---
2012/08/17 13:57:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('delete')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('issue/delete')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=issue/delete&id=1
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/view&id=1
---
2012/08/17 13:58:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('issue/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=issue/admin
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2012/08/17 13:59:00 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('delete')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('issue/delete')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=issue/delete&id=1
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/view&id=1
---
2012/08/17 14:04:26 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "textDropDown".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('textDropDown', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/trackstar/protected/views/issue/_form.php(44): CActiveForm->textDropDown(Object(Issue), 'status_id', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(127): require('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(96): CBaseController->renderInternal('/Applications/X...', Array, true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(870): CBaseController->renderFile('/Applications/X...', Array, true)
#5 /Applications/XAMPP/xamppfiles/htdocs/trackstar/protected/views/issue/create.php(18): CController->renderPartial('_form', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(127): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(96): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(870): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(783): CController->renderPartial('create', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/protected/controllers/IssueController.php(79): CController->render('create', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(50): IssueController->actionCreate()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(41): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('create')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('issue/create')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2012/08/17 14:04:27 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "textDropDown".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('textDropDown', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/trackstar/protected/views/issue/_form.php(44): CActiveForm->textDropDown(Object(Issue), 'status_id', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(127): require('/Applications/X...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(96): CBaseController->renderInternal('/Applications/X...', Array, true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(870): CBaseController->renderFile('/Applications/X...', Array, true)
#5 /Applications/XAMPP/xamppfiles/htdocs/trackstar/protected/views/issue/create.php(18): CController->renderPartial('_form', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(127): require('/Applications/X...')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(96): CBaseController->renderInternal('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(870): CBaseController->renderFile('/Applications/X...', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(783): CController->renderPartial('create', Array, true)
#10 /Applications/XAMPP/xamppfiles/htdocs/trackstar/protected/controllers/IssueController.php(79): CController->render('create', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(50): IssueController->actionCreate()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(41): CFilterChain->run()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(283): CController->run('create')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('issue/create')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/trackstar/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
